In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
from pprint import pprint

In [18]:
TARGET_FOLDER = Path('../../data/features/')

**One-hot vector as node feature**
1. read edgelist file
2. extract all nodes
3. one-hot encode all nodes
4. return df with two column [node, onehot]

In [6]:
FILE_NAME = 'GM12878_PPI_sample_ver1.csv'
DATA_FOLDER = Path('../../data/')

# 1. Read edgelist
df = pd.read_csv(DATA_FOLDER / FILE_NAME)
df.shape

(22639, 5)

In [14]:
# 2. Extract all nodes
nodes = set(df['source']).union(set(df['target']))
nodes = list(nodes)
nodes.sort()
node_df = pd.DataFrame(nodes)

           0
0       AAAS
1       AACS
2      AAGAB
3       AAMP
4       AARS
...      ...
7922  ZYG11A
7923  ZYG11B
7924     ZYX
7925   ZZEF1
7926   eIF2A

[7927 rows x 1 columns]

In [21]:
# Create one-hot encoding df
onehot_df = pd.get_dummies(node_df, prefix='node')

# Convert to np array and check whether it's diagnal matrix
# onehot = onehot_df.to_numpy()
# if np.count_nonzero(onehot - np.diag(np.diagonal(onehot))) == 0:
#     print("It's a diagnal matrix")

onehot_df.index = nodes
onehot_df

,node_AAAS,node_AACS,node_AAGAB,node_AAMP,node_AARS,node_AARS2,node_AARSD1,node_AASDHPPT,node_AASS,node_AATF,...,node_ZSWIM3,node_ZUFSP,node_ZW10,node_ZWILCH,node_ZWINT,node_ZYG11A,node_ZYG11B,node_ZYX,node_ZZEF1,node_eIF2A
AAAS,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AACS,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAGAB,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AAMP,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AARS,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZYG11A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
ZYG11B,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
ZYX,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
ZZEF1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
eIF2A,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [22]:
onehot_df.to_csv(TARGET_FOLDER / f'{FILE_NAME[:-4]}_onehot_names.csv', index=True)

****